storage:
  tsdb:
    out_of_order_time_window: 30m

scrape_configs:
  - job_name: keycloak
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
          - keycloak:9000

otlp:
