kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "crucible.fullname" . }}-topomojo-api-nfs
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
