{{- /* Persist postgres account password on a chart reinstall */ -}}
{{- $postgresPassword := "" }}
{{- $postgresqlSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-postgresql" (include "crucible.fullname" .)) }}
{{- if $postgresqlSecret }}
{{-   $postgresPassword = index $postgresqlSecret.data "postgres-password" | b64dec }}
{{- else }}
{{-   $postgresPassword = randAlphaNum 16 }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" . }}-postgresql
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  postgres-password: {{ $postgresPassword | b64enc | quote }}

---
{{- $keycloakSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-keycloak-auth" (include "crucible.fullname" .)) -}}
{{- $keycloakAdminPassword := randAlphaNum 16 -}}
{{- $keycloakOauthClientSecret := (randBytes 16 | b64dec | printf "%032x") -}}
{{- $keycloakDefaultUserGuid := uuidv4 -}}

{{- if and $keycloakSecret (hasKey $keycloakSecret.data "admin-password") -}}
  {{- $keycloakAdminPassword = (index $keycloakSecret.data "admin-password" | b64dec) -}}
{{- end }}
{{- if and $keycloakSecret (hasKey $keycloakSecret.data "oauth-client-secret") -}}
  {{- $keycloakOauthClientSecret = (index $keycloakSecret.data "oauth-client-secret" | b64dec) -}}
{{- end }}
{{- if and $keycloakSecret (hasKey $keycloakSecret.data "default-user-guid") -}}
  {{- $keycloakDefaultUserGuid = (index $keycloakSecret.data "default-user-guid" | b64dec) -}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" . }}-keycloak-auth
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  admin-password: {{ $keycloakAdminPassword }}
  oauth-client-secret: {{ $keycloakOauthClientSecret }}
  default-user-guid: {{ $keycloakDefaultUserGuid }}

---
{{- /* TODO: Share oauth-client-secret and move this back to configmap.yaml */ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crucible.fullname" . }}-keycloak-config-cli
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
data:
  realm.json: |-
{{ (.Files.Get "files/crucible-realm.json" | nindent 4) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" $ }}-topomojo-api-custom
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
type: Opaque
stringData:
  appsettings.conf: |
    Database__ConnectionString = Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=topomojo;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;
    Database__AdminId = {{ $keycloakDefaultUserGuid }}
  cacert.crt: |
    {{- (.Files.Get "files/crucible-dev.crt" | nindent 4) }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" $ }}-gameboard-api-custom
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
type: Opaque
stringData:
  Database__ConnectionString: Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=gameboard;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;
  Database__AdminId: {{ $keycloakDefaultUserGuid }}

---
{{- $tlsSecretName := printf "%s-cert" .Release.Name | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $tlsSecretName }}
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/tls
data:
  tls.crt: {{ (.Files.Get "files/crucible-dev.crt" | b64enc) | quote }}
  tls.key: {{ (.Files.Get "files/crucible-dev.key" | b64enc) | quote }}
