{{- /* Persist postgres account password on a chart reinstall */ -}}
{{- $postgresPassword := "" }}
{{- $postgresqlSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-postgresql" (include "crucible.fullname" .)) }}
{{- if $postgresqlSecret }}
{{-   $postgresPassword = index $postgresqlSecret.data "postgres-password" | b64dec }}
{{- else }}
{{-   $postgresPassword = randAlphaNum 16 }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" . }}-postgresql
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  postgres-password: {{ $postgresPassword | b64enc | quote }}

---
{{- $keycloakSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-keycloak-auth" (include "crucible.fullname" .)) -}}
{{- $keycloakAdminPassword := randAlphaNum 16 -}}
{{- $keycloakOauthClientSecret := (randBytes 16 | b64dec | printf "%032x") -}}
{{- $keycloakDefaultUserGuid := uuidv4 -}}

{{- if and $keycloakSecret (hasKey $keycloakSecret.data "admin-password") -}}
  {{- $keycloakAdminPassword = (index $keycloakSecret.data "admin-password" | b64dec) -}}
{{- end }}
{{- if and $keycloakSecret (hasKey $keycloakSecret.data "oauth-client-secret") -}}
  {{- $keycloakOauthClientSecret = (index $keycloakSecret.data "oauth-client-secret" | b64dec) -}}
{{- end }}
{{- if and $keycloakSecret (hasKey $keycloakSecret.data "default-user-guid") -}}
  {{- $keycloakDefaultUserGuid = (index $keycloakSecret.data "default-user-guid" | b64dec) -}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" . }}-keycloak-auth
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  admin-password: {{ $keycloakAdminPassword }}
  oauth-client-secret: {{ $keycloakOauthClientSecret }}
  default-user-guid: {{ $keycloakDefaultUserGuid }}

---
{{- /* TODO: Share oauth-client-secret and move this back to configmap.yaml */ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crucible.fullname" . }}-keycloak-config-cli
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
data:
  realm.json: |-
{{ (.Files.Get "files/crucible-realm.json" | nindent 4) }}
---
{{- $alloyValues := default dict (index $.Values "alloy") -}}
{{- $alloyApiValues := default dict (index $alloyValues "alloy-api") -}}
{{- $resourceOwnerAuthorization := default dict (index $alloyApiValues "resourceOwnerAuthorization") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" $ }}-alloy-api-custom
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__PostgreSQL: Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=alloy;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;
  ResourceOwnerAuthorization__Authority: {{ tpl (default "" (index $resourceOwnerAuthorization "authority")) $ | quote }}
  ResourceOwnerAuthorization__ClientId: {{ tpl (default "" (index $resourceOwnerAuthorization "clientId")) $ | quote }}
  ResourceOwnerAuthorization__ClientSecret: {{ tpl (default "" (index $resourceOwnerAuthorization "clientSecret")) $ | quote }}
  ResourceOwnerAuthorization__UserName: {{ tpl (default "" (index $resourceOwnerAuthorization "userName")) $ | quote }}
  ResourceOwnerAuthorization__Password: {{ tpl (default "" (index $resourceOwnerAuthorization "password")) $ | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" $ }}-topomojo-api-custom
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
type: Opaque
stringData:
  appsettings.conf: |
    Database__ConnectionString = Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=topomojo;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" $ }}-player-api-custom
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__PostgreSQL: Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=player;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" $ }}-vm-api-custom
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__PostgreSQL: Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=player_vm;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;
  VmUsageLogging__PostgreSQL: Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=player_vm_logging;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" $ }}-blueprint-api-custom
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__PostgreSQL: Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=blueprint;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;
  ResourceOwnerAuthorization__Password: {{ $keycloakOauthClientSecret }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" $ }}-cite-api-custom
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__PostgreSQL: Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=cite;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" $ }}-gallery-api-custom
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__PostgreSQL: Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=gallery;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;

---
{{- $gameboardValues := default dict (index $.Values "gameboard") -}}
{{- $gameboardApiValues := default dict (index $gameboardValues "gameboard-api") -}}
{{- $gameEngineClientSecret := default "" (index $gameboardApiValues "gameEngineClientSecret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" $ }}-gameboard-api-custom
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
type: Opaque
stringData:
  Database__ConnectionString: Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=gameboard;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;
  GameEngine__ClientSecret: {{ tpl $gameEngineClientSecret $ | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" $ }}-caster-api-custom
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__PostgreSQL: Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=caster;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;
  Client__Password: {{ $keycloakOauthClientSecret }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" $ }}-steamfitter-api-custom
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__PostgreSQL: Server={{ include "crucible.fullname" $ }}-postgresql;Port=5432;Database=steamfitter;Username=postgres;Password={{ $postgresPassword }};SSL Mode=Prefer;Trust Server Certificate=true;
  ResourceOwnerAuthorization__Password: {{ $keycloakOauthClientSecret }}

---
{{- $pgadminSecretName := "crucible-pgadmin" -}}
{{- $pgadminSecret := lookup "v1" "Secret" .Release.Namespace $pgadminSecretName -}}
{{- $pgadminPassword := randAlphaNum 16 -}}
{{- if and $pgadminSecret (hasKey $pgadminSecret.data "password") -}}
  {{- $pgadminPassword = (index $pgadminSecret.data "password" | b64dec) -}}
{{- end }}
{{- $pgadminServers := dict "Servers" (dict "crucible-postgres" (dict
    "Name" "Crucible Postgres"
    "Group" "Servers"
    "Host" (printf "%s-postgresql" (include "crucible.fullname" $))
    "Port" 5432
    "Username" "postgres"
    "SSLMode" "prefer"
    "MaintenanceDB" "postgres"
  )) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $pgadminSecretName }}
  labels:
    {{- include "crucible.labels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  password: {{ $pgadminPassword }}
  servers.json: |
    {{- $pgadminServers | toPrettyJson | nindent 4 }}

---
{{- $tlsSecretName := printf "%s-cert" .Release.Name | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $tlsSecretName }}
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/tls
data:
  tls.crt: {{ (.Files.Get "files/crucible-dev.crt" | b64enc) | quote }}
  tls.key: {{ (.Files.Get "files/crucible-dev.key" | b64enc) | quote }}
