#!/bin/bash
# Copyright 2026 Carnegie Mellon University. All Rights Reserved.
# Released under a MIT (SEI)-style license. See LICENSE.md in the project root for license information.
#
# Generates xdebug_filter.php dynamically based on repos.json and repos.local.json

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$SCRIPT_DIR/repos.json"
LOCAL_MANIFEST="$SCRIPT_DIR/repos.local.json"
OUTPUT="$SCRIPT_DIR/../Crucible.AppHost/resources/moodle/xdebug_filter.php"

echo "Generating xdebug_filter.php..."

# Function to map Moodle plugin names to container paths
map_plugin_to_container_path() {
    local plugin_name="$1"
    local plugin_type=$(echo "$plugin_name" | cut -d '_' -f 1)
    local plugin_subdir=$(echo "$plugin_name" | cut -d '_' -f 2-)

    case "$plugin_type" in
        mod) echo "/var/www/html/mod/$plugin_subdir" ;;
        block) echo "/var/www/html/blocks/$plugin_subdir" ;;
        tool) echo "/var/www/html/admin/tool/$plugin_subdir" ;;
        logstore) echo "/var/www/html/admin/tool/log/store/$plugin_subdir" ;;
        local) echo "/var/www/html/local/$plugin_subdir" ;;
        qtype) echo "/var/www/html/question/type/$plugin_subdir" ;;
        qbehaviour) echo "/var/www/html/question/behaviour/$plugin_subdir" ;;
        aiplacement) echo "/var/www/html/ai/placement/$plugin_subdir" ;;
        qformat) echo "/var/www/html/question/format/$plugin_subdir" ;;
        theme) echo "/var/www/html/theme/$plugin_subdir" ;;
        *) echo "/var/www/html/$plugin_type/$plugin_subdir" ;;
    esac
}

# Merge repos.json and repos.local.json if local exists
if [ -f "$LOCAL_MANIFEST" ]; then
    echo "  Merging repos.json + repos.local.json..."
    MANIFEST_DATA=$(jq -s '
        .[0] as $base | .[1] as $local |
        {
            groups: ($base.groups + ($local.groups // [])),
            repos: ($base.repos + ($local.repos // []))
        }
    ' "$MANIFEST" "$LOCAL_MANIFEST")
else
    echo "  Using repos.json only (repos.local.json not found)..."
    MANIFEST_DATA=$(cat "$MANIFEST")
fi

# Start generating the PHP file
cat > "$OUTPUT" <<'HEADER'
<?php
// Copyright 2026 Carnegie Mellon University. All Rights Reserved.
// Released under a MIT (SEI)-style license. See LICENSE.md in the project root for license information.
//
// AUTO-GENERATED by scripts/generate-xdebug-filter.sh
// DO NOT EDIT MANUALLY - Changes will be overwritten

// Set coverage and debugging for just our repos and bind-mounted directories
$includePaths = [
    // Core Moodle paths (always included)
    "/var/www/html/theme",
    "/var/www/html/lib",
    "/var/www/html/admin/cli",
    "/var/www/html/ai/provider",
    "/var/www/html/ai/classes",
HEADER

# Extract moodle plugins and add their container paths
echo "  Processing Moodle plugins..."
echo "$MANIFEST_DATA" | jq -r '
    .groups[] |
    select(.name == "moodle") |
    .repos[].name
' | sort -u | while read -r plugin_name; do
    if [ -n "$plugin_name" ]; then
        container_path=$(map_plugin_to_container_path "$plugin_name")
        echo "    \"$container_path\"," >> "$OUTPUT"
        echo "    - $plugin_name -> $container_path"
    fi
done

# Add PHP footer
cat >> "$OUTPUT" <<'FOOTER'
];

if (extension_loaded('xdebug') && !empty($includePaths)) {
    // Filter code coverage
    xdebug_set_filter(
        XDEBUG_FILTER_CODE_COVERAGE,
        XDEBUG_PATH_INCLUDE,
        $includePaths
    );

    // Filter tracing/debugging to prevent "Unknown sourceReference 0" errors
    // This limits step debugging to only the directories we have locally
    xdebug_set_filter(
        XDEBUG_FILTER_TRACING,
        XDEBUG_PATH_INCLUDE,
        $includePaths
    );
}
FOOTER

echo "✓ Generated $OUTPUT"
