<?php
// Copyright 2026 Carnegie Mellon University. All Rights Reserved.
// Released under a MIT (SEI)-style license. See LICENSE.md in the project root for license information.
//
// AUTO-GENERATED by scripts/generate-xdebug-filter.sh
// DO NOT EDIT MANUALLY - Changes will be overwritten

// Set coverage and debugging for just our repos and bind-mounted directories
$includePaths = [
    // Core Moodle paths (always included)
    "/var/www/html/theme",
    "/var/www/html/lib",
    "/var/www/html/admin/cli",
    "/var/www/html/ai/provider",
    "/var/www/html/ai/classes",
    "/var/www/html/ai/placement/competency",
    "/var/www/html/ai/provider/bedrock",
    "/var/www/html/blocks/crucible",
    "/var/www/html/local/tagmanager",
    "/var/www/html/admin/tool/log/store/xapi",
    "/var/www/html/mod/crucible",
    "/var/www/html/mod/groupquiz",
    "/var/www/html/mod/pptbook",
    "/var/www/html/mod/topomojo",
    "/var/www/html/question/behaviour/mojomatch",
    "/var/www/html/question/type/mojomatch",
    "/var/www/html/admin/tool/lptmanager",
];

if (extension_loaded('xdebug') && !empty($includePaths)) {
    // Filter code coverage
    xdebug_set_filter(
        XDEBUG_FILTER_CODE_COVERAGE,
        XDEBUG_PATH_INCLUDE,
        $includePaths
    );

    // Filter tracing/debugging to prevent "Unknown sourceReference 0" errors
    // This limits step debugging to only the directories we have locally
    xdebug_set_filter(
        XDEBUG_FILTER_TRACING,
        XDEBUG_PATH_INCLUDE,
        $includePaths
    );
}
